add AutoSwitchElytra
ThinkingStudios/Tweakeroo-Forge pull request #15
Opened 2024-08-14 02:54 UTC by JackieJK

2024-08-14 15:03 UTC, TexBlock requested changes

2024-08-14 15:03 UTC, TexBlock commented on .github/workflows/gradle.yml
remove this file plz

2024-08-14 17:00 UTC, JackieJK commented on .github/workflows/gradle.yml
ok

2024-08-15 03:57 UTC, TexBlock approved these changes

2024-08-15 03:57 UTC, TexBlock commented
Thanks your pr!

2024-08-15 03:57 UTC, merged